title: Sarah B. Carey
locale: en_US
description: -omics and code enthusiast
logo: scarey.jpg
search: true
url: sarahcarey.github.io

# Jekyll configuration
remote_theme: "mmistakes/jekyll-theme-slate"
markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

# Site owner
owner:
  name: Sarah B. Carey
  avatar: SCarey.jpg
  email: sarah.carey@ufl.edu
  twitter: sarahbcarey
  github: sarahcarey
  

